services:
 frontend:
   container_name: frontend 
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "80:80"
   networks:
     - app_network


networks:
  app_network:
    external: true